---
- name: Installing tomcat10 in ubuntu 22.04
  hosts: all
  become: yes
  tasks:
    - name: Installing java 11 
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: true
        state: present

    - name: Adding the group for tomcat10
      ansible.builtin.group:
        name: tomcat
        state: present

    - name: Adding the user for tomcat10
      ansible.builtin.user:
        name: tomcat
        create_home: true
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
  
    - name: downloading tomcat10 tar file
      ansible.builtin.get_url:
        url: https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.4/bin/apache-tomcat-10.1.4.tar.gz
        dest: /tmp

    - name: unarchiving the tar file
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/apache-tomcat-10.1.4.tar.gz
        dest: /opt/tomcat/
      
    - name: creating system soft link 
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.1.4
        state: link
        dest: /opt/tomcat/latest

    - name: Assigning ownership to tomcat user on the file
      ansible.builtin.file:
        path: /opt/tomcat
        owner: tomcat
        recurse: true

    - name: Making tomcat/bin file executable
      ansible.builtin.shell: sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
      
    - name: Creating a tomcat.service file in /etc/ folder
      ansible.builtin.copy:
        remote_src: no
        src: ./unit.service
        dest: /etc/systemd/system/tomcat.service 
    
    - name: Reloading/enabling/starting the daemon files
      ansible.builtin.systemd:
        name: tomcat.service
        daemon_reload: true
        enabled: true
        state: restarted
    
